### ISSUE TITLE
"Copy Link" should use "www"

### ISSUE THREAD

**Issue by impressivewebs** [sitepoint/wp-band-aid#19]
This is just a small thing, but technically SitePoint always uses "www" in front of its URLs so the "copy link" functionality should do that too. Right now, it copies "http://sitepoint.com" instead of "http://www.sitepoint.com" which just feels so naked! :)

**Comment by impressivewebs** [comment]
I just added a PR: https://github.com/sitepoint/wp-band-aid/pull/20

**Comment by Swader** [comment]
Merged :)
