### ISSUE TITLE
Preloading screen

### ISSUE THREAD

**Issue by Swader** [sitepoint/wp-band-aid#2]
Due to the extensive number of UI changes the extension does to the default WP UI, perhaps some kind of preloading screen (a cover to hide the main screen until all loading it done) would be better of UX?

Needs discussion - could potentially be more distracting than the jittering itself.

**Comment by jameshibbard** [comment]
Not a problem I have run into. Did this ever cause issues for you?

**Comment by Swader** [comment]
Yes. I often have many tabs open, and a slow connection. This in tandem makes the screen load slowly, showing everything pre-render, and then snapping into post-render. Most distractingly, this is the upgrade box at the top of the screen. A faster way to handle this would be to make a new matches block in the manifest file and load a single CSS file which makes the upgrade box display:none, and this matches block should load not on document_idle like the rest of them, but as early as possible. That would make the box never appear (in theory) thus removing the jump without the need for additional screens or javascript hacks.

**Comment by jameshibbard** [comment]
By upgrade box do you mean the W3 Total Cache banner?

**Comment by Swader** [comment]
Yes, that, but also the "there is a new version available" which I'd like to be rid of too.

**Comment by jameshibbard** [comment]
This should do the trick: https://github.com/sitepoint/wp-band-aid/pull/34

**Comment by Swader** [comment]
Closed via #34
