### ISSUE TITLE
Reminder to check URL slug

### ISSUE THREAD

**Issue by AdamRobertsNZ** [sitepoint/wp-band-aid#22]
Feature request - a pop-up to remind editors to check over the URL slug before saving/scheduling an article. We’ve been having articles go out with a bunch of numbers as the URL slug lately. It’s really tricky to work out what’s going on so a reminder to make sure a slug is correct would be helpful, and would at least rule out human error as a cause. If possible, having the pop-up only appear when a URL is a bunch of numbers would be perfect, but a general one would work as well.

**Comment by jameshibbard** [comment]
Would it be sufficient to flag a slug consisting only of numbers (whereas one which contains any other characters is accepted)?

`http://www.sitepoint.com/123456/` — gets flagged
`htpp://www.sitepoint.com/123456a/` — doesn't

If not, can you narrow down what you mean by "when a URL is a bunch of numbers"?

**Comment by Swader** [comment]
I think it'd be most useful to check for how many words a URL slug contains. Anything less than 2 is suspicious, and automatically eliminates numerical URLs. That's super easy to check for and reasonably safe. Would that work?

**Comment by jameshibbard** [comment]
So count the number of minus signs in a slug? Slugs with less than two(?) minus signs get flagged.

**Comment by Swader** [comment]
No, that would mark sitepoint.com/------ as OK. Either a simple regex looking for sets of word characters between minuses, or exploding a string on minuses and counting the characters in the resulting elements would be the ways to go.

**Comment by jameshibbard** [comment]
PR submitted (https://github.com/sitepoint/wp-band-aid/pull/23).
This is just to get the ball rolling — regex can be changed as necessary, but covers main use case.
Would appreciate feedback (esp. as this adds an event listener to _Publish_ button).
