### ISSUE TITLE
Add HTML > MD conversion.

### ISSUE THREAD

**Issue by jameshibbard** [sitepoint/wp-band-aid#33]
Would be nice to have HTML > MD conversion.
This would be useful when asking an author to update a post that is not in the repo (as then you could generate a MD version automatically and have the author work in that).

**Comment by Swader** [comment]
Would we ignore custom inline CSS and html that MD doesn't support? For example, centering images, or images with width/height?

**Comment by jameshibbard** [comment]
Yep. Would be sufficient for my purposes initially. I also couldn't find a plugin that uses backticks to mark code blocks. I tried several and they all indent using 4 spaces. I have a bunch of reg exs that work quite well.

**Comment by jameshibbard** [comment]
This might be useful. https://github.com/Khan/simple-markdown
